apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-redis-pvc
  namespace: gitlab
spec:
  storageClassName: gluster-heketi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi